// SPDX-License-Identifier: MIT
// Copyright (c) vecnode
//
// Builds the global-scope object bag a JS-interpreted sketch runs against -
// the same names a real Arduino sketch uses (pinMode, digitalWrite, HIGH,
// Serial.println, ...), bound to one ArduinoRuntime instance.

import { LiquidCrystal } from './liquid-crystal';
import { ArduinoRuntime, type PinMode } from './runtime';

export const HIGH = 1;
export const LOW = 0;
export const INPUT: PinMode = 'input';
export const OUTPUT: PinMode = 'output';
export const INPUT_PULLUP: PinMode = 'input_pullup';
// Real hardware fact, not a physicalsim convention: every classic AVR
// Arduino board this runtime targets (Uno/Nano/Mega/Leonardo) wires its
// onboard LED to pin 13 (confirmed against each board's own
// pins_arduino.h - Mega2560's LED_BUILTIN is 13 too, despite having 54
// digital pins).
export const LED_BUILTIN = 13;

/**
 * Arduino's `Serial` object, TX-only (matching every real adapter's
 * current scope - see AVRUSART/adapter.ts's own onSerialData). `begin()`
 * is a no-op (no real baud-rate/framing to configure without a real
 * UART peripheral) kept only so sketches that call `Serial.begin(9600)`
 * don't need editing to run here.
 */
export class SketchSerial {
  constructor(private readonly runtime: ArduinoRuntime) {}

  begin(baud: number): void {
    void baud; // no-op: see class doc comment.
  }

  write(byte: number): void {
    this.runtime.writeSerialByte(byte);
  }

  print(value: unknown): void {
    const text = String(value);
    for (let i = 0; i < text.length; i++) {
      this.runtime.writeSerialByte(text.charCodeAt(i));
    }
  }

  println(value: unknown = ''): void {
    this.print(value);
    this.runtime.writeSerialByte(0x0d);
    this.runtime.writeSerialByte(0x0a);
  }
}

// The bound LiquidCrystal constructor a sketch sees - same 6-arg
// (rs, enable, d4, d5, d6, d7) shape real Arduino sketches call
// (`LiquidCrystal lcd(12, 11, 5, 4, 3, 2);`), with `runtime` already
// captured so sketch code never needs to know it exists.
export type SketchLiquidCrystal = new (
  rs: number,
  enable: number,
  d4: number,
  d5: number,
  d6: number,
  d7: number,
) => LiquidCrystal;

export interface SketchGlobals {
  pinMode: (pin: number, mode: PinMode) => void;
  digitalWrite: (pin: number, value: 0 | 1 | boolean) => void;
  digitalRead: (pin: number) => 0 | 1;
  analogWrite: (pin: number, value: number) => void;
  analogRead: (pin: number) => number;
  millis: () => number;
  micros: () => number;
  delay: (ms: number) => void;
  delayMicroseconds: (us: number) => void;
  Serial: SketchSerial;
  LiquidCrystal: SketchLiquidCrystal;
  HIGH: number;
  LOW: number;
  INPUT: PinMode;
  OUTPUT: PinMode;
  INPUT_PULLUP: PinMode;
  LED_BUILTIN: number;
  // A0.. constants - how many exist, and which numeric pin each maps to,
  // depends on the board shape (Uno/Nano/Leonardo: A0-A5 = pins 14-19;
  // Mega: A0-A15 = pins 54-69), so these are generated by
  // createSketchGlobals() below rather than fixed here.
  [analogConstant: `A${number}`]: number;
}

export interface SketchGlobalsOptions {
  /** Digital pin count - where the A0.. constants start counting from. Defaults to 14 (Uno/Nano/Leonardo's shape). */
  digitalPinCount?: number;
  /** How many A0.. constants to generate. Defaults to 6 (Uno/Nano/Leonardo's shape); Mega needs 16. */
  analogPinCount?: number;
}

export function createSketchGlobals(
  runtime: ArduinoRuntime,
  options: SketchGlobalsOptions = {},
): SketchGlobals {
  const digitalPinCount = options.digitalPinCount ?? 14;
  const analogPinCount = options.analogPinCount ?? 6;
  const analogConstants: Record<string, number> = {};
  for (let i = 0; i < analogPinCount; i++) {
    analogConstants[`A${i}`] = digitalPinCount + i;
  }

  return {
    pinMode: (pin, mode) => runtime.pinMode(pin, mode),
    digitalWrite: (pin, value) => runtime.digitalWrite(pin, value ? 1 : 0),
    digitalRead: (pin) => runtime.digitalRead(pin),
    analogWrite: (pin, value) => runtime.analogWrite(pin, value),
    analogRead: (pin) => runtime.analogRead(pin),
    millis: () => runtime.millis(),
    micros: () => runtime.micros(),
    delay: (ms) => runtime.delay(ms),
    delayMicroseconds: (us) => runtime.delayMicroseconds(us),
    Serial: new SketchSerial(runtime),
    LiquidCrystal: class extends LiquidCrystal {
      constructor(rs: number, enable: number, d4: number, d5: number, d6: number, d7: number) {
        super(runtime, rs, enable, d4, d5, d6, d7);
      }
    },
    HIGH,
    LOW,
    INPUT,
    OUTPUT,
    INPUT_PULLUP,
    LED_BUILTIN,
    ...analogConstants,
  };
}

export interface CompiledSketch {
  setup: () => void;
  loop: () => void;
}

/**
 * Interprets sketch source text as a JS function body exposing `setup`
 * and `loop` (either `function setup() {...}` declarations, matching real
 * Arduino sketch shape, or `const setup = () => {...}`) against the given
 * globals - no compiler involved, this is `new Function(...)` running the
 * sketch's own top-level code once to capture its declared setup/loop,
 * then handing back those two functions for the caller's own scheduler
 * to invoke. Runs whatever scope calls this in (a Worker, in
 * physicalsim's case - see ARCHITECTURE.md's adapter-worker isolation),
 * which is the sandboxing boundary: no DOM/network access from inside a
 * Worker, same posture a real compiled sketch's machine code already had.
 */
export function compileSketch(source: string, globals: SketchGlobals): CompiledSketch {
  const globalNames = Object.keys(globals);
  const globalValues = Object.values(globals);
  const factory = new Function(
    ...globalNames,
    `"use strict";\n${source}\nreturn { setup: typeof setup === 'function' ? setup : function(){}, loop: typeof loop === 'function' ? loop : function(){} };`,
  ) as (...args: unknown[]) => CompiledSketch;
  const compiled = factory(...globalValues);
  if (typeof compiled.setup !== 'function' || typeof compiled.loop !== 'function') {
    throw new Error('Sketch must define setup() and loop() functions');
  }
  return compiled;
}
